### ISSUE TITLE
id lookups do not work with urn-based id

### ISSUE THREAD

**Issue by Hokua** [vistadataproject/VICSServer#331]
they work with the last number in the urn id, example urn:vista:999:2:17 => 17.

This is true for allergyLookup and removeAllergies

**Comment by mfuroyama** [comment]
Added [VAM-688](https://hawaiirg.atlassian.net/browse/VAM-688) in Jira VAM project for tracking

**Comment by mfuroyama** [comment]
@kekuso ended up reworking all the endpoints to use URNs.
