### ISSUE TITLE
createProblem: no argument for Historic Visit

### ISSUE THREAD

**Issue by Hokua** [vistadataproject/VICSServer#363]
The Historic Visit check box is available in CPRS, however the REST service does not have this option.

**Comment by mfuroyama** [comment]
@kekuso @sidjtd @Hokua 

It's not totally clear from the documentation, but when you create a problem that is associated with a historical visit context, that date can be set in the `createProblem` endpoint by setting the `interestDate` field in the HTTP message body. This is the field that gets set in the RPC when using CPRS when the "Historic Visit" checkbox is selected. Will close this as a quasi-OBE
